name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true

      - name: Run tests
        run: |
          make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: tmp/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: tmp/test-report.xml
          token: ${{ secrets.CODECOV_TOKEN }}